[package]
name = "rulespec-nz"
version = "0.1.0"
edition = "2021"

[lib]
name = "rulespec_nz"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.21.0", features = ["extension-module"] }
arrow = "51.0"
polars = { version = "0.38.0", features = ["lazy"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
wasm-bindgen = "0.2"
chrono = "=0.4.38"

